name: .NET Build, Test and Publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - run: |
          echo "Hello Build job!!!!"
          
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository      
      - run: |
          echo "Hello Test job!!!!"

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository      
      - run: |
          echo "Hello Publish job!!!!"
